241105
jihyun-jeon/ts-algorithm pull request #1
Opened 2024-11-05 14:23 UTC by jihyun-jeon

코딩테스트 코드리뷰 요청드립니다 :)

2024-11-08 15:31 UTC, f-lab-jake requested changes

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv1.같은 숫자는 싫어-스택,큐.ts
> +    if (result[result.length - 1] !== n) {
`at`을 쓰세요.

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv1.같은 숫자는 싫어-스택,큐.ts
> +  const result: Array<number> = [];
`number[]`를 쓰세요.

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv1.약수의합-구현.ts
> +  let geun = Math.floor(Math.sqrt(num));
변수명을 영어로 쓰세요.

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv1.약수의합-구현.ts
> +    if (yaksu % 1 === 0) {
무슨 의도지요?

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv1.포켓몬-해시.ts
> +  });
`filter`롸 `Map` 초기화를 활용하세요.

2024-11-08 15:31 UTC, f-lab-jake commented on 프로그래머스/lv2.기능개발-스택,큐.ts
> +  }
중복을 제거하세요.

2024-11-12 02:32 UTC, jihyun-jeon commented on 프로그래머스/lv1.약수의합-구현.ts
> +    if (yaksu % 1 === 0) {
num을 제곱근으로 나눴을때 정수가 나오는지 판별하려는 의도였습니다.
isInteger를 사용하는게 더 나을 것 같네요!

2024-11-12 02:34 UTC, jihyun-jeon commented
피드백 내용 반영하여 다시 푸시했습니다!

2024-11-12 08:49 UTC, f-lab-jake requested changes

2024-11-12 08:49 UTC, f-lab-jake commented on 프로그래머스/lv1.약수의합-구현.ts
> +    if (Number.isInteger(dividedBySqrt)) {
`divrem`이란 함수를 만들어 사용하세요. 그리고 변수명도 `div` `rem` 이렇게 써도됩니다.

2024-11-12 08:49 UTC, f-lab-jake commented on 프로그래머스/lv1.약수의합-구현.ts
> +  let sqrtValue = Math.floor(Math.sqrt(num));
뒤에 `value`는 아무 의미가없습니다. 차라리 `sqrtOfNum`하던가, 아니면 그냥 `sqrt`해도 되겠네요.

2024-11-12 08:49 UTC, f-lab-jake commented on 프로그래머스/lv1.포켓몬-해시.ts
> +    return self.indexOf(n) === idx;
`indexOf` 안쓰는 방식으로 고쳐보세요

2024-11-13 13:52 UTC, jihyun-jeon commented
코드 재수정 하였습니다! [439abdb](https://github.com/jihyun-jeon/ts-algorithm/pull/1/commits/439abdb1b06ece09159b4934b624755bb0138d1b)

2024-11-14 12:39 UTC, f-lab-jake requested changes

2024-11-14 12:39 UTC, f-lab-jake commented on 프로그래머스/lv1.약수의합-구현.ts
> +function divRem(num: number, s: number): [boolean, number] {
`divrem`의 정의는 이런식이 아닙니다. 몫/나머지를 반환해야합니다. 그게 왜 더 나은 정의인지 고민해보세요.

2024-11-16 04:17 UTC, f-lab-jake approved these changes

2024-11-17 13:05 UTC, merged