241107
jihyun-jeon/ts-algorithm pull request #2
Opened 2024-11-07 13:33 UTC by jihyun-jeon

코드리뷰 요청드립니다 :)

2024-11-08 15:34 UTC, f-lab-jake requested changes

2024-11-08 15:34 UTC, f-lab-jake commented on 프로그래머스/lv1.k번째수-정렬.ts
> +    const [first, second, target] = command;
잘했습니다.

2024-11-08 15:34 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +    const rightIdx = reserve.findIndex((r) => r === l + 1);
비효율을 제거하세요.

2024-11-08 15:34 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +    if (leftIdx > -1) {
!== -1 을 쓰세요. 그게 왜 나을까요?

2024-11-08 15:34 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +    const rightIdx = reserve.findIndex((r) => r === l + 1);
애초에 좀더 자료구조를 잘 설계하면 가능합니다.

2024-11-08 15:34 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +  }
이건 i가 체육복을 좌우로 주는 방식이죠? i가 양쪽에서 받도록 고쳐보세요.

2024-11-12 03:03 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +    const rightIdx = reserve.findIndex((r) => r === l + 1);
배열이 아닌 Set을 활용하도록 수정했습니다.
인덱스를 계산할 필요가 없어 더 깔끔해졌네요!

2024-11-12 03:09 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +  }
네 내용 반영하여 다시 푸쉬했습니다. [455c265](https://github.com/jihyun-jeon/ts-algorithm/pull/2/commits/455c265f23421f40d188a1ecfe7c429444cc023f)

2024-11-12 03:15 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +    if (leftIdx > -1) {
leftIdx가 어떤 수이든 -1만 아니면 되서
더 직관적이기 때문이라고 생각됩니다.

2024-11-12 08:53 UTC, f-lab-jake approved these changes
잘했습니다. 내일 마저 얘기하죠.

2024-11-13 13:54 UTC, jihyun-jeon commented
멘토링시 피드백 주신 내용으로 체육복 문제 개선했습니다! [2df1bf7](https://github.com/jihyun-jeon/ts-algorithm/pull/2/commits/2df1bf785092de504c5b679e4dc6b4f1fad040c2)

2024-11-14 12:42 UTC, f-lab-jake requested changes

2024-11-14 12:42 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +    } else if (isLost && students[right] > 1) {
여기 else를 사실 빼도되는데요. 빼고 말고 어떤차이가 있을까요?

2024-11-15 10:12 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +    } else if (isLost && students[right] > 1) {
<else를 빼고 안빼고의 차이>
**if문 ~ else if 문**  
- if문 조건이 참이면 , else if 실행되지X
- if문 조건이 거짓이면 , else if 실행ㅇ

**if문1 ~ if 문2**  
- if문1 조건이 참이든 거짓이든, if문2 실행ㅇ

2024-11-15 10:14 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +    } else if (isLost && students[right] > 1) {
이 문제에서는 else if문으로 해야 될 것 같아요!

else를 빼면 [2,0,2] 인 경우 0이 왼쪽에서도, 오른쪽에서도
두번 빌려오게 되서 오답이 나오네요~

2024-11-16 04:19 UTC, f-lab-jake commented on 프로그래머스/lv1.체육복-그리디.ts
> +    } else if (isLost && students[right] > 1) {
`isLost`를 빼고 else도 빼보세요. 이게 무조건 더좋은건 아닌데, 그렇게해놓고 비교해보세요.

2024-11-17 14:12 UTC, jihyun-jeon commented on 프로그래머스/lv1.체육복-그리디.ts
> +    } else if (isLost && students[right] > 1) {
아 어떤 의도인지 이해했습니다!
처음 if문 실행에서 student 상태가 확정됨에 따라 하위 로직이 실행되는거군요

코드 개선했습니다! [4c9a947](https://github.com/jihyun-jeon/ts-algorithm/pull/2/commits/4c9a947690f54e2bdb8588ed52e0579051127ffe)

2024-11-18 02:50 UTC, f-lab-jake approved these changes

2024-11-21 03:19 UTC, merged