Week5
jihyun-jeon/ts-algorithm pull request #5
Opened 2024-12-08 07:41 UTC by jihyun-jeon

5주차 코드리뷰 요청드립니다 :)

코테합(코딩테스트 합격자되기 책) 풀이 보며 개선사항도 파악해보았습니다.

2024-12-09 01:49 UTC, f-lab-jake requested changes

2024-12-09 01:49 UTC, f-lab-jake commented on 프로그래머스/배열/lv1.모의고사-완전탐색.ts
> +  }
`scores`를 수정하지마세요. hint: `map`을 쓰세요

2024-12-09 01:49 UTC, f-lab-jake commented on 프로그래머스/스택/lv2.올바른괄호.ts
> +    const top = stack[stack.length - 1];
`at`쓰세요

2024-12-09 01:49 UTC, f-lab-jake commented on 프로그래머스/배열/lv2.방문길이-구현.ts
> +    const path2 = `${x2}${y2}${x}${y}`;
`path`에 필요 이상의 자유도가 있습니다. 가령 대각선으로 이동하는 틀린 `path`도 포함해버릴수 있씁니다.
`d`를 포함시키세요.

2024-12-11 08:51 UTC, jihyun-jeon commented
피드백 반영하여 코드 수정했습니다!
[d4c2202](https://github.com/jihyun-jeon/ts-algorithm/pull/5/commits/d4c2202e6620682d8e182b27201f9626dba79d9c)

2024-12-16 07:48 UTC, f-lab-jake requested changes

2024-12-16 07:48 UTC, f-lab-jake commented on 프로그래머스/배열/lv2.방문길이-구현.ts
> +    const path2 = `${x2}${y2}${x}${y}${reverseD}`;
더 줄일수있습니다

2024-12-16 07:48 UTC, f-lab-jake commented on 프로그래머스/배열/lv2.방문길이-구현.ts
> +    const path2 = `${x2}${y2}${x}${y}${reverseD}`;
문자열안의 모든 변수들이 독립이 아니에요

2024-12-17 06:16 UTC, jihyun-jeon commented on 프로그래머스/배열/lv2.방문길이-구현.ts
> +    const path2 = `${x2}${y2}${x}${y}${reverseD}`;
path1,2의 중복을 제거하여
하나의 path 로 개선했습니다!
[2f7c4c6](https://github.com/jihyun-jeon/ts-algorithm/pull/5/commits/2f7c4c6d50bd6ae627f4099f39059ac1c36fb530)

2024-12-19 14:55 UTC, jihyun-jeon commented
[67b8292](https://github.com/jihyun-jeon/ts-algorithm/pull/5/commits/67b82924914f6f597d6bf271fe0b6d4360536861)
코드 재개선 했습니다!

- path값을 `x,y,d` 구조로 단순화

- 역방향을 정방향과 동일한 경로로 처리
ex) 00 → 01 `00U` , 01 → 00 `01D`
      둘다 `00U` 라는 경로로 처리

2024-12-30 18:06 UTC, merged